version: '3.3'

services:
  wordpress_angular:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./bekend:/var/www/html/wp-content/themes/bekend
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: dbpassword
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: dbpassword
    networks:
      - back  
networks:
  back:
volumes:
  db_data:
